import * as CONSTANTS from "../config/constants.js";
import Cancel from "./Cancel.js";
import Move from "./Move.js";
import Stop from "./Stop.js";
import AttackMelee from "./AttackMelee.js";
import AttackRanged from "./AttackRanged.js";
import Summon from "./Summon.js";
import Extract from "./Extract.js";
import Repair from "./Repair.js";
import BuildRoad from "./BuildRoad.js";
import BuildStandard from "./BuildStandard.js";
import BuildAdvanced from "./BuildAdvanced.js";
import Build from "./Build.js";
import Produce from "./Produce.js";
import Buff from "./Buff.js";

let abilities = new Map();

abilities.set(CONSTANTS.ABILITY_CANCEL, Cancel);
abilities.set(CONSTANTS.ABILITY_MOVE, Move);
abilities.set(CONSTANTS.ABILITY_STOP, Stop);
abilities.set(CONSTANTS.ABILITY_REPAIR, Repair);
abilities.set(CONSTANTS.ABILITY_EXTRACT, Extract);
abilities.set(CONSTANTS.ABILITY_ATTACK_MELEE, AttackMelee);
abilities.set(CONSTANTS.ABILITY_ATTACK_STING, AttackMelee);
abilities.set(CONSTANTS.ABILITY_ATTACK_CREATURE, AttackMelee);
abilities.set(CONSTANTS.ABILITY_ATTACK_RANGED, AttackRanged);
abilities.set(CONSTANTS.ABILITY_ATTACK_LANCE, AttackMelee);
abilities.set(CONSTANTS.ABILITY_ATTACK_CANNON, AttackRanged);
abilities.set(CONSTANTS.ABILITY_ATTACK_SPELL, AttackRanged);
abilities.set(CONSTANTS.ABILITY_ATTACK_FIREBALL, AttackRanged);
abilities.set(CONSTANTS.ABILITY_BUFF, Buff);
abilities.set(CONSTANTS.ABILITY_SUMMON_COMPANION, Summon);
abilities.set(CONSTANTS.ABILITY_SUMMON_CREATURE, Summon);
abilities.set(CONSTANTS.ABILITY_BUILD_ROAD, BuildRoad);
abilities.set(CONSTANTS.ABILITY_BUILD_STANDARD, BuildStandard);
abilities.set(CONSTANTS.ABILITY_BUILD_ADVANCED, BuildAdvanced);
abilities.set(CONSTANTS.ABILITY_BUILD_FARM, Build);
abilities.set(CONSTANTS.ABILITY_BUILD_BARRACKS, Build);
abilities.set(CONSTANTS.ABILITY_BUILD_LUMBER_MILL, Build);
abilities.set(CONSTANTS.ABILITY_BUILD_BLACKSMITH, Build);
abilities.set(CONSTANTS.ABILITY_BUILD_STABLE, Build);
abilities.set(CONSTANTS.ABILITY_BUILD_CHURCH, Build);
abilities.set(CONSTANTS.ABILITY_BUILD_TOWER, Build);
abilities.set(CONSTANTS.ABILITY_PRODUCE_WORKER, Produce);
abilities.set(CONSTANTS.ABILITY_PRODUCE_SOLDIER, Produce);
abilities.set(CONSTANTS.ABILITY_PRODUCE_SHOOTER, Produce);
abilities.set(CONSTANTS.ABILITY_PRODUCE_CAVALRY, Produce);
abilities.set(CONSTANTS.ABILITY_PRODUCE_CATAPULT, Produce);
abilities.set(CONSTANTS.ABILITY_PRODUCE_MAGE, Produce);
abilities.set(CONSTANTS.ABILITY_PRODUCE_SUMMONER, Produce);

export default abilities;
