import * as CONSTANTS from './constants.js';


export default {
    [CONSTANTS.TYPE_ENTITY_UNIT]: [
        CONSTANTS.ENTITY_WORKER,
        CONSTANTS.ENTITY_SOLDIER,
        CONSTANTS.ENTITY_SHOOTER,
        CONSTANTS.ENTITY_CAVALRY,
        CONSTANTS.ENTITY_CATAPULT,
        CONSTANTS.ENTITY_MAGE,
        CONSTANTS.ENTITY_SUMMONER,
        CONSTANTS.ENTITY_COMPANION,
        CONSTANTS.ENTITY_CREATURE,
    ],

    [CONSTANTS.TYPE_ENTITY_BUILDING]: [
        CONSTANTS.ENTITY_GOLD_MINE,
        CONSTANTS.ENTITY_FARM,
        CONSTANTS.ENTITY_TOWN_HALL,
        CONSTANTS.ENTITY_BARRACKS,
        CONSTANTS.ENTITY_LUMBER_MILL,
        CONSTANTS.ENTITY_BLACKSMITH,
        CONSTANTS.ENTITY_STABLE,
        CONSTANTS.ENTITY_CHURCH,
        CONSTANTS.ENTITY_TOWER,
    ],

    [CONSTANTS.TYPE_ENTITY_COWARD]: [
        CONSTANTS.ENTITY_WORKER,
    ],

    [CONSTANTS.TYPE_ENTITY_FIGHTER]: [
        CONSTANTS.ENTITY_SOLDIER,
        CONSTANTS.ENTITY_SHOOTER,
        CONSTANTS.ENTITY_CAVALRY,
        CONSTANTS.ENTITY_CATAPULT,
        CONSTANTS.ENTITY_MAGE,
        CONSTANTS.ENTITY_SUMMONER,
        CONSTANTS.ENTITY_COMPANION,
        CONSTANTS.ENTITY_CREATURE,
    ],

    [CONSTANTS.TYPE_ABILITY_COMMON]: [
        CONSTANTS.ABILITY_CANCEL,
        CONSTANTS.ABILITY_MOVE,
        CONSTANTS.ABILITY_STOP,
    ],

    [CONSTANTS.TYPE_ABILITY_WORK]: [
        CONSTANTS.ABILITY_REPAIR,
        CONSTANTS.ABILITY_EXTRACT,
    ],

    [CONSTANTS.TYPE_ABILITY_ATTACK]: [
        CONSTANTS.ABILITY_ATTACK_MELEE,
        CONSTANTS.ABILITY_ATTACK_STING,
        CONSTANTS.ABILITY_ATTACK_CREATURE,
        CONSTANTS.ABILITY_ATTACK_RANGED,
        CONSTANTS.ABILITY_ATTACK_LANCE,
        CONSTANTS.ABILITY_ATTACK_CANNON,
        CONSTANTS.ABILITY_ATTACK_SPELL,
        CONSTANTS.ABILITY_ATTACK_FIREBALL,
    ],

    [CONSTANTS.TYPE_ABILITY_BUFF]: [
        CONSTANTS.ABILITY_BUFF,
    ],

    [CONSTANTS.TYPE_ABILITY_SUMMON]: [
        CONSTANTS.ABILITY_SUMMON_COMPANION,
        CONSTANTS.ABILITY_SUMMON_CREATURE,
    ],

    [CONSTANTS.TYPE_ABILITY_BUILD]: [
        CONSTANTS.ABILITY_BUILD_ROAD,
        CONSTANTS.ABILITY_BUILD_STANDARD,
        CONSTANTS.ABILITY_BUILD_ADVANCED,
        CONSTANTS.ABILITY_BUILD_FARM,
        CONSTANTS.ABILITY_BUILD_BARRACKS,
        CONSTANTS.ABILITY_BUILD_LUMBER_MILL,
        CONSTANTS.ABILITY_BUILD_BLACKSMITH,
        CONSTANTS.ABILITY_BUILD_STABLE,
        CONSTANTS.ABILITY_BUILD_CHURCH,
        CONSTANTS.ABILITY_BUILD_TOWER,
    ],

    [CONSTANTS.TYPE_ABILITY_CONSTRUCT]: [
        CONSTANTS.ABILITY_BUILD_FARM,
        CONSTANTS.ABILITY_BUILD_BARRACKS,
        CONSTANTS.ABILITY_BUILD_LUMBER_MILL,
        CONSTANTS.ABILITY_BUILD_BLACKSMITH,
        CONSTANTS.ABILITY_BUILD_STABLE,
        CONSTANTS.ABILITY_BUILD_CHURCH,
        CONSTANTS.ABILITY_BUILD_TOWER,
    ],

    [CONSTANTS.TYPE_ABILITY_PRODUCE]: [
        CONSTANTS.ABILITY_PRODUCE_WORKER,
        CONSTANTS.ABILITY_PRODUCE_SOLDIER,
        CONSTANTS.ABILITY_PRODUCE_SHOOTER,
        CONSTANTS.ABILITY_PRODUCE_CAVALRY,
        CONSTANTS.ABILITY_PRODUCE_CATAPULT,
        CONSTANTS.ABILITY_PRODUCE_MAGE,
        CONSTANTS.ABILITY_PRODUCE_SUMMONER,
    ],
};
