import * as CONSTANTS from "../config/constants.js";
import map from "../maps/campaign_human_7.js";
import TacticalAi from "../ai/TacticalAi.js";

export default {
    game: {
        player: CONSTANTS.RACE_HUMAN,
        terrain: CONSTANTS.TERRAIN_FOREST,
    },

    scrollStart: {
        x: 0,
        y: 3,
    },

    resources: {
        lumber: 500,
        gold: 300,
    },

    tiles: map,

    road: [
        [5, 8], [5, 9], [5, 10], [5, 11], [5, 12], [5, 13], [5, 14], [3, 9], [4, 9], [3, 13], [4, 13], [43, 53],
        [44, 53], [45, 53], [46, 53], [47, 53], [51, 53], [52, 53], [53, 53], [54, 53], [55, 53], [42, 57],
        [43, 57], [44, 57], [45, 57], [46, 57], [47, 57], [48, 57], [49, 57], [50, 57], [51, 57], [52, 57],
        [53, 57], [54, 57], [55, 57], [56, 57], [43, 53], [43, 54], [43, 55], [43, 56], [43, 57], [47, 53],
        [47, 54], [47, 55], [47, 56], [47, 57], [47, 58], [47, 59], [51, 53], [51, 54], [51, 55], [51, 56],
        [51, 57], [51, 58], [51, 59], [55, 53], [55, 54], [55, 55], [55, 56], [55, 57], [55, 58],
    ],

    ais: {
        [CONSTANTS.RACE_ORC]: TacticalAi,
    },

    entities: [
        {
            type: CONSTANTS.ENTITY_GOLD_MINE,
            race: CONSTANTS.RACE_NEUTRAL,
            cellX: 27,
            cellY: 3,
        },
        {
            type: CONSTANTS.ENTITY_GOLD_MINE,
            race: CONSTANTS.RACE_NEUTRAL,
            cellX: 3,
            cellY: 24,
        },
        {
            type: CONSTANTS.ENTITY_GOLD_MINE,
            race: CONSTANTS.RACE_NEUTRAL,
            cellX: 8,
            cellY: 41,
        },
        {
            type: CONSTANTS.ENTITY_GOLD_MINE,
            race: CONSTANTS.RACE_NEUTRAL,
            cellX: 30,
            cellY: 58,
        },
        {
            type: CONSTANTS.ENTITY_GOLD_MINE,
            race: CONSTANTS.RACE_NEUTRAL,
            cellX: 35,
            cellY: 45,
        },
        {
            type: CONSTANTS.ENTITY_GOLD_MINE,
            race: CONSTANTS.RACE_NEUTRAL,
            cellX: 59,
            cellY: 7,
        },
        {
            type: CONSTANTS.ENTITY_TOWN_HALL,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 2,
            cellY: 10,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 3,
            cellY: 7,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 3,
            cellY: 14,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 6,
            cellY: 6,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 1,
            cellY: 8,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 6,
            cellY: 9,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 5,
            cellY: 11,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 8,
            cellY: 8,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 10,
            cellY: 9,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 9,
            cellY: 12,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 7,
            cellY: 13,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 11,
            cellY: 11,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 12,
            cellY: 9,
        },
        {
            type: CONSTANTS.ENTITY_MAGE,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 10,
            cellY: 7,
        },
        {
            type: CONSTANTS.ENTITY_MAGE,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 6,
            cellY: 12,
        },
        {
            type: CONSTANTS.ENTITY_CATAPULT,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 8,
            cellY: 10,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 53,
            cellY: 34,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 57,
            cellY: 34,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 54,
            cellY: 33,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 56,
            cellY: 33,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 56,
            cellY: 35,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 54,
            cellY: 35,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_HUMAN,
            cellX: 55,
            cellY: 32,
        },
        {
            type: CONSTANTS.ENTITY_TOWN_HALL,
            race: CONSTANTS.RACE_ORC,
            cellX: 48,
            cellY: 58,
        },
        {
            type: CONSTANTS.ENTITY_BARRACKS,
            race: CONSTANTS.RACE_ORC,
            cellX: 52,
            cellY: 54,
        },
        {
            type: CONSTANTS.ENTITY_CHURCH,
            race: CONSTANTS.RACE_ORC,
            cellX: 44,
            cellY: 54,
        },
        {
            type: CONSTANTS.ENTITY_LUMBER_MILL,
            race: CONSTANTS.RACE_ORC,
            cellX: 52,
            cellY: 58,
        },
        {
            type: CONSTANTS.ENTITY_BLACKSMITH,
            race: CONSTANTS.RACE_ORC,
            cellX: 45,
            cellY: 58,
        },
        {
            type: CONSTANTS.ENTITY_STABLE,
            race: CONSTANTS.RACE_ORC,
            cellX: 48,
            cellY: 55,
        },
        {
            type: CONSTANTS.ENTITY_TOWER,
            race: CONSTANTS.RACE_ORC,
            cellX: 58,
            cellY: 57,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_ORC,
            cellX: 56,
            cellY: 52,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_ORC,
            cellX: 56,
            cellY: 55,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_ORC,
            cellX: 56,
            cellY: 58,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_ORC,
            cellX: 42,
            cellY: 58,
        },
        {
            type: CONSTANTS.ENTITY_FARM,
            race: CONSTANTS.RACE_ORC,
            cellX: 41,
            cellY: 55,
        },
        {
            type: CONSTANTS.ENTITY_SOLDIER,
            race: CONSTANTS.RACE_ORC,
            cellX: 33,
            cellY: 46,
        },
        {
            type: CONSTANTS.ENTITY_SOLDIER,
            race: CONSTANTS.RACE_ORC,
            cellX: 50,
            cellY: 31,
        },
        {
            type: CONSTANTS.ENTITY_SOLDIER,
            race: CONSTANTS.RACE_ORC,
            cellX: 50,
            cellY: 35,
        },
        {
            type: CONSTANTS.ENTITY_SOLDIER,
            race: CONSTANTS.RACE_ORC,
            cellX: 37,
            cellY: 44,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 60,
            cellY: 31,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 48,
            cellY: 52,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 60,
            cellY: 34,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 32,
            cellY: 55,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 31,
            cellY: 56,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 52,
            cellY: 44,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 57,
            cellY: 47,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 43,
            cellY: 57,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 30,
            cellY: 57,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 53,
            cellY: 45,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 55,
            cellY: 57,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 55,
            cellY: 46,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 51,
            cellY: 60,
        },
        {
            type: CONSTANTS.ENTITY_SHOOTER,
            race: CONSTANTS.RACE_ORC,
            cellX: 47,
            cellY: 60,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_ORC,
            cellX: 50,
            cellY: 33,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_ORC,
            cellX: 43,
            cellY: 53,
        },
        {
            type: CONSTANTS.ENTITY_CAVALRY,
            race: CONSTANTS.RACE_ORC,
            cellX: 54,
            cellY: 52,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_ORC,
            cellX: 47,
            cellY: 57,
        },
        {
            type: CONSTANTS.ENTITY_WORKER,
            race: CONSTANTS.RACE_ORC,
            cellX: 51,
            cellY: 57,
        },
    ],
}
